groupe_index:
    path:     /
    defaults: { _controller: "UserBundle:Groupe:index" }
    methods:  GET

groupe_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:Groupe:show" }
    methods:  GET

groupe_new:
    path:     /new
    defaults: { _controller: "UserBundle:Groupe:new" }
    methods:  [GET, POST]

groupe_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:Groupe:edit" }
    methods:  [GET, POST]

groupe_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:Groupe:delete" }
    methods:  DELETE
