UserBundle\Entity\Groupe:
    type: entity
    table: null
    repositoryClass: UserBundle\Repository\GroupeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255


    lifecycleCallbacks: {  }
