user_adherent:
    resource: "@UserBundle/Resources/config/routing/adherent.yml"
    prefix:   /adherent

user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Dashboard:index }

user_tools:
        resource: "@UserBundle/Resources/config/routing/tools.yml"
        prefix:   /tools

user_groupe:
        resource: "@UserBundle/Resources/config/routing/groupe.yml"
        prefix:   /groupe

user_message:
        resource: "@UserBundle/Resources/config/routing/message.yml"
        prefix:   /message
